services:

  afa-postgres:
    container_name: afa-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    profiles:
      - cloud
      - local

  afa-discovery:
    container_name: afa-discovery
    image: afa-discovery
    ports:
      - "8761:8761"
    build:
      context: "afa-discovery"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      PORT: 8761
    profiles:
      - cloud

  afa-config:
    container_name: afa-config
    image: afa-config
    ports:
      - "8888:8888"
    build:
      context: "afa-config"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      DISCOVERY_SERVER_URL: http://afa-discovery:8761/eureka
      PORT: 8888

      # other services configs

        # gateway
      AFA_USER_NAME: afa-user
      AFALOAN_NAME: afaloan

        # afa-user
      AFA_USER_R2DBC_URL: r2dbc:postgresql://localhost:5432/afa_user
      AFA_USER_JDBC_URL: jdbc:postgresql://localhost:5432/afa_user
      AFA_USER_DB_USER: username
      AFA_USER_DB_PASSWORD: password
      SECRET: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
      ACCESS: 1
      REFRESH: 24

        # afaloan
      AFALOAN_JDBC_URL: jdbc:postgresql://localhost:5432/afaloan
      AFALOAN_DB_USER: username
      AFALOAN_DB_PASSWORD: password

    depends_on:
      - afa-discovery
    profiles:
      - cloud

  afa-admin:
    container_name: afa-admin
    image: afa-admin
    ports:
      - "8187:8187"
    build:
      context: "afa-admin"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://afa-discovery:8761/eureka
      PORT: 8187
    depends_on:
      - afa-discovery
      - afa-config
    profiles:
      - cloud

  afa-gateway:
    container_name: afa-gateway
    image: afa-gateway
    ports:
      - "8080:8080"
    build:
      context: "afa-gateway"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://afa-discovery:8761/eureka
      API_PREFIX: api/v2
      PORT: 8080
    depends_on:
      - afa-discovery
      - afa-config
    profiles:
      - cloud

  afa-user:
    container_name: afa-user
    image: afa-user
    ports:
      - "8383:8383"
    build:
      context: "afa-user"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://afa-discovery:8761/eureka
      PORT: 8383
    depends_on:
      - afa-postgres
      - afa-discovery
      - afa-config
      - afa-gateway
    profiles:
      - cloud

  afaloan:
    container_name: afaloan
    image: afaloan
    ports:
      - "8381:8381"
    build:
      context: "Afaloan"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://afa-discovery:8761/eureka
      PORT: 8381
    depends_on:
      - afa-postgres
      - afa-discovery
      - afa-config
      - afa-gateway
    profiles:
      - cloud
