spring:
  services:
    urls:
      afa-user: ${AFA_USER_NAME:afa-user}
      afaloan: ${AFALOAN_NAME:afaloan}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
