spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/afaloan}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  s3:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:username}
    secret-key: ${MINIO_SECRET_KEY:password}
    bucket: ${MINIO_BUCKET:afaloan}
    region: ${MINIO_REGION:us-east-1}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
