spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${AFALOAN_JDBC_URL:jdbc:postgresql://localhost:5432/afaloan}
    username: ${AFALOAN_DB_USER:username}
    password: ${AFALOAN_DB_PASSWORD:password}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
